import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import '../../features/translation/presentation/pages/capture_page.dart';
import '../../features/translation/presentation/pages/history_page.dart';
import '../../features/translation/presentation/pages/translation_detail_page.dart';
import '../../features/translation/domain/entities/translation_entity.dart';

part 'app_router.gr.dart'; // Generated by build_runner

@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    AutoRoute(page: CaptureRoute.page, initial: true),
    AutoRoute(page: HistoryRoute.page),
    AutoRoute(page: TranslationDetailRoute.page),
  ];
}